#!/bin/bash
#
# center-window

# moves the currently active window to the center of the 
# display its center lies in.

# gets the current position of the window focussed
curr_window=$(xdotool getactivewindow getwindowgeometry)
window_pos=$( echo $curr_window | grep "Position" | grep -o "[0-9]*,[0-9]*" )
window_geo=$( echo $curr_window | grep "Geometry" | grep -o "[0-9]*x[0-9]*" )
window_left=$( echo $window_pos | cut -d "," -f 1 )
window_top=$( echo $window_pos | cut -d "," -f 2 )
window_width=$( echo $window_geo | cut -d "x" -f 1 )
window_height=$( echo $window_geo | cut -d "x" -f 2 )
window_right=$(( $window_left + $window_width ))
window_bottom=$(( $window_top + $window_height ))
window_x=$(( ($window_left + $window_right) / 2 ))
window_y=$(( ($window_top + $window_bottom) / 2 ))

# holds the coordinates of the closest location to which the window
# should be moved if the center doesn't lie in a monitor
move_to_x=""
move_to_y=""
move_to_dist=""

for display in $( xrandr | 
                  grep -o "[0-9]*x[0-9]*+[0-9]*+[0-9]*" | 
                  sed "s:\([0-9]*\)x\([0-9]*\)+\([0-9]*\)+\([0-9]*\):\1;\2;\3;\4:" ) 
do
  # sets all of the dimensions of the current monitor being handled
  display_width=$( echo $display | cut -d ";" -f 1 )
  display_height=$( echo $display | cut -d ";" -f 2 )
  display_left=$( echo $display | cut -d ";" -f 3 )
  display_top=$( echo $display | cut -d ";" -f 4 )
  display_right=$(( $display_left + $display_width ))
  display_bottom=$(( $display_top + $display_height ))
  display_x=$(( ($display_left + $display_right) / 2 ))
  display_y=$(( ($display_top + $display_bottom) / 2 ))

  potential_x=$(( $display_x - ($window_width / 2) ))
  potential_y=$(( $display_y - ($window_height / 2) ))
  potential_dist=$(( ($window_x - $potential_x)**2 + ($window_y - $potential_y)**2 ))

  # tests to see if the window in in the current display
  if [[ $window_x -ge $display_left ]] &&
     [[ $window_x -le $display_right ]] &&
     [[ $window_y -ge $display_top ]] &&
     [[ $window_y -le $display_bottom ]] 
  then
    # centers the window to the current display
    xdotool getactivewindow windowmove "$potential_x" "$potential_y"
    exit 0
  else
    if [ -z $move_to_x ] || 
       [ -z $move_to_y ] || 
       [ -lt $potential_dist $move_to_dist ] 
    then
      move_to_x=$potential_x
      move_to_y=$potential_y
      move_to_dist=$potential_dist
    fi
  fi
done

xdotool getactivewindow windowmove "$move_to_x" "$move_to_y"
exit 0
